name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: big-brother-x86_64
          - runs-on: ubuntu-24.04-arm64
            target: aarch64-unknown-linux-gnu
            asset_name: big-brother-arm64
    
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Rename binary
      run: cp target/release/big-brother ${{ matrix.asset_name }}
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
